### ISSUE TITLE
ModuleNotFoundError: No module named 'mdtraj'

### ISSUE THREAD

**Issue by mozhde** [MarsalekGroup/aml#5]
Hello, I am trying to use the "score-all.py" to validate my trajectories but this error pops up 
" ModuleNotFoundError: No module named 'mdtraj' "
I tried to replace the line " import mdtraj as mdt " with " from aml.io import mdtraj as mdt ", but then I get another error 
"AttributeError: module 'aml.io.mdtraj' has no attribute 'load_frame' "
I was wondering if you could help me fix this issue.

Cheers
Mozhdeh

**Comment by cschran** [comment]
Dear Mozhdeh,

the scoring module requires the mdtraj package, which can be easily installed via
```
$ conda install -c conda-forge mdtraj
```
This should fix your problems.

Cheers,
Christoph

**Comment by mozhde** [comment]
Got it. Thank you.
